### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by MLBlocks** [Kortemme-Lab/ddg#2]
Hello,
My research team us using your ddG benchmark dataset for a project we are working on. Can I know how we can cite your benchmark dataset?
Much appreciated!

Thanks!

**Comment by kylebarlow** [comment]
Please cite the paper this benchmark was a part of:

A Web Resource for Standardized Benchmark Datasets, Metrics, and Rosetta Protocols for Macromolecular Modeling and Design 
Ó Conchúir S, Barlow KA, Pache RA, Ollikainen N, Kundert K, et al. (2015) A Web Resource for Standardized Benchmark Datasets, Metrics, and Rosetta Protocols for Macromolecular Modeling and Design. PLOS ONE 10(9): e0130433. https://doi.org/10.1371/journal.pone.0130433

Thanks!
